export class  CommonConstants {
  static readonly Size:number = 50
  /**
   * Full percent.
   */
  static readonly FULL_PERCENT: string = '100%';
  /**
   * Foldable percent.
   */
  static readonly Foldable_PERCENT: string = '70%';
  /**
   * None percent.
   */
  static readonly NONE_PERCENT: string = '0';
  /**
   * Swiper initially currentIndex.
   */
  static readonly INITIALLY_CURRENT_INDEX: number = -1;
  /**
   * Swiper slide index.
   */
  static readonly SLIDE_INDEX: number = -1;
  /**
   * Swiper image duration.
   */
  static readonly IMAGE_DURATION: number = 300;
  /**
   * Swiper duration.
   */
  static readonly DURATION: number = 3000;
  /**
   * Swiper interval.
   */
  static readonly INTERVAL: number = 3000;
  /**
   * Swiper item space.
   */
  static readonly ITEM_SPACE: number = 0;
  /**
   * Swiper interval duration.
   */
  static readonly INITIALLY_DURATION: number = 300;
  /**
   * Swiper duration.
   */
  static readonly NO_DURATION: number = 0;
  /**
   * Swiper max height.
   */
  static readonly SWIPER_MAX_HEIGHT: number = 333;
  /**
   * Swiper cached count.
   */
  static readonly SWIPER_CACHED_COUNT: number = 2;
  /**
   * Progress wrap height.
   */
  static readonly PROGRESS_WRAP_HEIGHT: number = 50;
  /**
   * zIndex.
   */
  static readonly Z_INDEX_0: number = 0;
  /**
   * zIndex.
   */
  static readonly Z_INDEX_1: number = 1;
  /**
   * zIndex.
   */
  static readonly Z_INDEX_2: number = 2;
  /**
   * zIndex.
   */
  static readonly Z_INDEX_3: number = 3;
  /**
   * Swiper initially Index.
   */
  static readonly INITIALLY_INDEX: number = 0;
  /**
   * Layout weight.
   */
  static readonly LAYOUT_WEIGHT: number = 1;
  /**
   * Column height.
   */
  static readonly COLUMN_HEIGHT: number = 100;
  /**
   * Multipart form text weight.
   */
  static readonly FORM_TEXT_FONT_WEIGHT: number = 500;
  /**
   * Row space.
   */
  static readonly ROW_SPACE: number = 5;
  /**
   * Column space.
   */
  static readonly COLUMN_SPACE: number = 16;
  /**
   * Column space inside.
   */
  static readonly COLUMN_SPACE_INSIDE: number = 8;
}